# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('micro', '0002_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_recommendation_given',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_date', models.DateTimeField(verbose_name=b'recommend date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_with_rec', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
