# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0003_time_recommendation_given'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='recommended_user',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='weight',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=6),
        ),
    ]
