# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('micro', '0005_remove_recommendation_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='recommended_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_recommended', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='weight',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=6),
        ),
    ]
