# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='backend.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rbackend.proto\":\n\x0f\x46ollowerRequest\x12\x10\n\x08MainUser\x18\x01 \x01(\t\x12\x15\n\rSubscriptions\x18\x02 \x03(\t\"$\n\x13RecommendationReply\x12\r\n\x05Users\x18\x01 \x03(\t\"\x1c\n\x0blistOfUsers\x12\r\n\x05names\x18\x01 \x03(\t2\xe3\x01\n\x11GenerateFollowers\x12\x32\n\x06logic1\x12\x10.FollowerRequest\x1a\x14.RecommendationReply\"\x00\x12\x32\n\x06logic2\x12\x10.FollowerRequest\x1a\x14.RecommendationReply\"\x00\x12\x32\n\x06logic3\x12\x10.FollowerRequest\x1a\x14.RecommendationReply\"\x00\x12\x32\n\x06logic4\x12\x10.FollowerRequest\x1a\x14.RecommendationReply\"\x00\x62\x06proto3')
)




_FOLLOWERREQUEST = _descriptor.Descriptor(
  name='FollowerRequest',
  full_name='FollowerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MainUser', full_name='FollowerRequest.MainUser', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Subscriptions', full_name='FollowerRequest.Subscriptions', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=75,
)


_RECOMMENDATIONREPLY = _descriptor.Descriptor(
  name='RecommendationReply',
  full_name='RecommendationReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Users', full_name='RecommendationReply.Users', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=113,
)


_LISTOFUSERS = _descriptor.Descriptor(
  name='listOfUsers',
  full_name='listOfUsers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='names', full_name='listOfUsers.names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['FollowerRequest'] = _FOLLOWERREQUEST
DESCRIPTOR.message_types_by_name['RecommendationReply'] = _RECOMMENDATIONREPLY
DESCRIPTOR.message_types_by_name['listOfUsers'] = _LISTOFUSERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FollowerRequest = _reflection.GeneratedProtocolMessageType('FollowerRequest', (_message.Message,), dict(
  DESCRIPTOR = _FOLLOWERREQUEST,
  __module__ = 'backend_pb2'
  # @@protoc_insertion_point(class_scope:FollowerRequest)
  ))
_sym_db.RegisterMessage(FollowerRequest)

RecommendationReply = _reflection.GeneratedProtocolMessageType('RecommendationReply', (_message.Message,), dict(
  DESCRIPTOR = _RECOMMENDATIONREPLY,
  __module__ = 'backend_pb2'
  # @@protoc_insertion_point(class_scope:RecommendationReply)
  ))
_sym_db.RegisterMessage(RecommendationReply)

listOfUsers = _reflection.GeneratedProtocolMessageType('listOfUsers', (_message.Message,), dict(
  DESCRIPTOR = _LISTOFUSERS,
  __module__ = 'backend_pb2'
  # @@protoc_insertion_point(class_scope:listOfUsers)
  ))
_sym_db.RegisterMessage(listOfUsers)



_GENERATEFOLLOWERS = _descriptor.ServiceDescriptor(
  name='GenerateFollowers',
  full_name='GenerateFollowers',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=146,
  serialized_end=373,
  methods=[
  _descriptor.MethodDescriptor(
    name='logic1',
    full_name='GenerateFollowers.logic1',
    index=0,
    containing_service=None,
    input_type=_FOLLOWERREQUEST,
    output_type=_RECOMMENDATIONREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='logic2',
    full_name='GenerateFollowers.logic2',
    index=1,
    containing_service=None,
    input_type=_FOLLOWERREQUEST,
    output_type=_RECOMMENDATIONREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='logic3',
    full_name='GenerateFollowers.logic3',
    index=2,
    containing_service=None,
    input_type=_FOLLOWERREQUEST,
    output_type=_RECOMMENDATIONREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='logic4',
    full_name='GenerateFollowers.logic4',
    index=3,
    containing_service=None,
    input_type=_FOLLOWERREQUEST,
    output_type=_RECOMMENDATIONREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GENERATEFOLLOWERS)

DESCRIPTOR.services_by_name['GenerateFollowers'] = _GENERATEFOLLOWERS

# @@protoc_insertion_point(module_scope)
