# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import backend_pb2 as backend__pb2


class GenerateFollowersStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.logic1 = channel.unary_unary(
        '/GenerateFollowers/logic1',
        request_serializer=backend__pb2.FollowerRequest.SerializeToString,
        response_deserializer=backend__pb2.RecommendationReply.FromString,
        )
    self.logic2 = channel.unary_unary(
        '/GenerateFollowers/logic2',
        request_serializer=backend__pb2.FollowerRequest.SerializeToString,
        response_deserializer=backend__pb2.RecommendationReply.FromString,
        )
    self.logic3 = channel.unary_unary(
        '/GenerateFollowers/logic3',
        request_serializer=backend__pb2.FollowerRequest.SerializeToString,
        response_deserializer=backend__pb2.RecommendationReply.FromString,
        )
    self.logic4 = channel.unary_unary(
        '/GenerateFollowers/logic4',
        request_serializer=backend__pb2.FollowerRequest.SerializeToString,
        response_deserializer=backend__pb2.RecommendationReply.FromString,
        )


class GenerateFollowersServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def logic1(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def logic2(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def logic3(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def logic4(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GenerateFollowersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'logic1': grpc.unary_unary_rpc_method_handler(
          servicer.logic1,
          request_deserializer=backend__pb2.FollowerRequest.FromString,
          response_serializer=backend__pb2.RecommendationReply.SerializeToString,
      ),
      'logic2': grpc.unary_unary_rpc_method_handler(
          servicer.logic2,
          request_deserializer=backend__pb2.FollowerRequest.FromString,
          response_serializer=backend__pb2.RecommendationReply.SerializeToString,
      ),
      'logic3': grpc.unary_unary_rpc_method_handler(
          servicer.logic3,
          request_deserializer=backend__pb2.FollowerRequest.FromString,
          response_serializer=backend__pb2.RecommendationReply.SerializeToString,
      ),
      'logic4': grpc.unary_unary_rpc_method_handler(
          servicer.logic4,
          request_deserializer=backend__pb2.FollowerRequest.FromString,
          response_serializer=backend__pb2.RecommendationReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'GenerateFollowers', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
