# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='backend.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rbackend.proto\" \n\nRecRequest\x12\x12\n\nMainUserId\x18\x01 \x01(\x05\"\x06\n\x04Void24\n\x11GenerateFollowers\x12\x1f\n\x07gen_rec\x12\x0b.RecRequest\x1a\x05.Void\"\x00\x62\x06proto3')
)




_RECREQUEST = _descriptor.Descriptor(
  name='RecRequest',
  full_name='RecRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MainUserId', full_name='RecRequest.MainUserId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=49,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=57,
)

DESCRIPTOR.message_types_by_name['RecRequest'] = _RECREQUEST
DESCRIPTOR.message_types_by_name['Void'] = _VOID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecRequest = _reflection.GeneratedProtocolMessageType('RecRequest', (_message.Message,), dict(
  DESCRIPTOR = _RECREQUEST,
  __module__ = 'backend_pb2'
  # @@protoc_insertion_point(class_scope:RecRequest)
  ))
_sym_db.RegisterMessage(RecRequest)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'backend_pb2'
  # @@protoc_insertion_point(class_scope:Void)
  ))
_sym_db.RegisterMessage(Void)



_GENERATEFOLLOWERS = _descriptor.ServiceDescriptor(
  name='GenerateFollowers',
  full_name='GenerateFollowers',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=59,
  serialized_end=111,
  methods=[
  _descriptor.MethodDescriptor(
    name='gen_rec',
    full_name='GenerateFollowers.gen_rec',
    index=0,
    containing_service=None,
    input_type=_RECREQUEST,
    output_type=_VOID,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GENERATEFOLLOWERS)

DESCRIPTOR.services_by_name['GenerateFollowers'] = _GENERATEFOLLOWERS

# @@protoc_insertion_point(module_scope)
